# name: deep3d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  # - pytorch=1.6.0
  # - torchvision=0.7.0
  - numpy
  - scikit-image
  - scipy
  - pillow
  - pip
  - ipython
  - yaml
  - pip:
    - matplotlib
    - opencv-python
    # - tensorboard==1.15.0
    # - tensorflow==1.15.0
    - kornia
    - dominate
    - trimesh
    - mtcnn
    - ninja
    - protobuf==3.20.0
    - flask
    - face-alignment
    # - imageio
    # - imageio-ffmpeg